/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  accepted_token: string[];
}
export type ExecuteMsg = {
  submit_social: {
    address: Addr;
    social_info: [string, string];
  };
} | {
  donate: {
    recipient: Addr;
  };
};
export type Addr = string;
export type QueryMsg = {
  get_addresses_by_social: {
    platform: string;
    profile_id: string;
  };
} | {
  get_socials_by_address: {
    address: Addr;
  };
};
export interface GetAddressesBySocialResponse {
  address: Addr[];
}
export interface GetSocialsByAddressResponse {
  social_infos: [string, string][];
}